spring:
  application:
    name: echeancier

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://dpg-d2h2db0gjchc73bo8ng0-a.oregon-postgres.render.com/echeancier_db
    username: echeancier_db_user
    password: BtxndSonF0GSZCq9nZ7nPGRSikcG1LYX
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    com.yoann.echeancier: DEBUG
    org.springframework.security: DEBUG

echeancier:
  jwtSecret: UneCleSecreteExempleComplexePourLeProjetEcheancierAvecBeaucoupDeCaracteresSpeciaux@12345
  jwtExpirationMs: 86400000 # 24 heures en millisecondes