spring:
  application:
    name: echeancier

  main:
    allow-bean-definition-overriding: true
  
  datasource:
    url: jdbc:h2:mem:echeancier
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.yoann.echeancier: DEBUG
    org.springframework.security: DEBUG